# helmpipeline_app_trtllm.yaml
apiVersion: v1
kind: Service
metadata:
  name: rag-llm-app
spec:
  type: NodePort  # Expose the service as a NodePort
  ports:
    - port: 80         # The port exposed inside the cluster
      targetPort: 8080  # The port the container listens on
      nodePort: 30080   # The specific port on the node where the service is exposed
  selector:
    app: rag-llm-app
